In [2]:
from src.data.dataset_loaders import TrainTestDataset, UnlearningDataLoader, UnlearningPairDataset
from torch.utils.data import DataLoader

# Create the dataset
unlearning_train_set = UnlearningPairDataset(
    csv_file="data/mnist_index.csv", 
    root_dir="data/softtarget_dataset/mnist",
    split='test'
)

# Use the custom DataLoader
unlearning_loader = UnlearningDataLoader(
    unlearning_train_set, 
    batch_size=2, 
    shuffle=True
)

Loading dataset index from data/mnist_index.csv...
Loaded Unlearning Dataset (test split): 6302 Forget samples and 63698 Non-Forget samples.


In [3]:
unlearning_loader.dataset.tensor_to_label

{tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]): '0',
 tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]): '1',
 tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]): '2',
 tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]): '3',
 tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]): '4',
 tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]): '5',
 tensor([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]): '6',
 tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]): '7',
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]): '8',
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]): '9'}

In [4]:
from torchvision.transforms import ToPILImage
from PIL import Image


for i in unlearning_loader:
    print(i.keys())
    for j in i.keys():
        print(i[j].keys())
        print(i[j]["input"].shape)
    print(i[j]["input"][0][2, 10])
    ToPILImage()(i[j]["input"][1]).show()
    break

dict_keys(['forget', 'retain'])
dict_keys(['input', 'labels', 'metadata'])
torch.Size([2, 3, 28, 28])
dict_keys(['input', 'labels', 'metadata'])
torch.Size([2, 3, 28, 28])
tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0196, 0.9098,
        0.9922, 0.9922, 0.9843, 0.8039, 0.0431, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0275, 0.6431, 0.9922, 0.9647, 0.1490, 0.0000, 0.0000,
        0.0000])


In [5]:
ttd = TrainTestDataset(
    csv_file="data/mnist_index.csv", 
    root_dir="data/softtarget_dataset/mnist",
    split='test'
)

for i in range(len(ttd)):
    sample, target = ttd[i]
    print(sample.shape)
    print(target.shape)
    print(ttd.get_tags(0))
    ToPILImage()(sample[1]).show()
    break


Loading dataset index from data/mnist_index.csv...
Loaded test split with 70000 samples.
torch.Size([3, 28, 28])
torch.Size([10])
{'index': 0, 'Path': 'data/softtarget_dataset/mnist/0/test_10.png', 'Class_Label': 0, 'train_split': 0, 'f1_split': 0}
