In [1]:
from src.data.dataset_loaders import TrainTestDataset, UnlearningDataLoader, UnlearningPairDataset
from torch.utils.data import DataLoader

# Create the dataset
unlearning_train_set = UnlearningPairDataset(
    csv_file="data/mnist_index.csv", 
    root_dir="data/softtarget_dataset/mnist",
    split='test'
)

# Use the custom DataLoader
unlearning_loader = UnlearningDataLoader(
    unlearning_train_set, 
    batch_size=2, 
    shuffle=True
)

Loading dataset index from data/mnist_index.csv...
Loaded Unlearning Dataset (test split using 'f1_split'): 889 Forget samples and 9111 Non-Forget samples.


In [14]:
len(unlearning_loader)

3151

In [15]:
unlearning_loader.dataset.tensor_to_label

{tensor([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]): '0',
 tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]): '1',
 tensor([0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]): '2',
 tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]): '3',
 tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]): '4',
 tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]): '5',
 tensor([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]): '6',
 tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]): '7',
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]): '8',
 tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]): '9'}

In [21]:
ttd = TrainTestDataset(
    csv_file="data/mnist_index.csv", 
    root_dir="data/softtarget_dataset/mnist",
    split='test',
    sample_mode='forget',
    classes=['7', '8', '9']
)



Loading dataset index from data/mnist_index.csv...
Loaded test split (mode='forget', classes=['7', '8', '9']) with 6302 samples.
